services:
  postgres:
    container_name: social-media
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      POSTGRES_DB: social-media
      POSTGRES_PASSWORD: mawuli302
      POSTGRES_USER: mawuli
      PGDATA: /data/postgres
    ports:
      - "5444:5432"

    restart: always

volumes:
  db:
